name: Deploy Profile MFE to S3

on:
  push:
    branches:
      - main # Deploy on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # 4️⃣ Cache pnpm store (speeds up installs)
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 5️⃣ Install dependencies & build Profile MFE
      - name: Install & build Profile MFE
        working-directory: profile
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      - name: Install & build Home MFE
        working-directory: home
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      # 6️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your AWS region

      # 7️⃣ Deploy Profile MFE to S3
      - name: Deploy Profile MFE to S3
        run: aws s3 sync profile/dist s3://${{ secrets.S3_BUCKET_NAME }}/profile --delete
      - name: Deploy Home MFE to S3
        run: aws s3 sync home/dist s3://${{ secrets.S3_BUCKET_NAME }}/ --delete
